name: Deploy to CH2.0

on:
  pull_request:
    branches: [ dev ]
    types: [ closed ]  # Triggers when a PR is closed (merged or not)

jobs:
  deploy:
    #Ensures the workflow runs only if the PR was merged
    if: github.event.pull_request.merged == true  
    runs-on: 
      group: gps-github-test-runners
    timeout-minutes: 15
    environment: DEV
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      
      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dmule.env=dev \
          -Dconnected_app_client_id=${{ secrets.connected_app_client_id }} \
          -Dconnected_app_client_secret=${{ secrets.connected_app_client_secret }} \
          -Dclient.id=${{ secrets.anypoint_client_id }} \
          -Dclient.secret=${{ secrets.anypoint_client_secret }} 

      - name: Deploy to CloudHub 2.0
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dmule.env=dev \
          -Dmule.key=${{ secrets.mule_key }} \
          -Dconnected_app_client_id=${{ secrets.connected_app_client_id }} \
          -Dconnected_app_client_secret=${{ secrets.connected_app_client_secret }} \
          -Dclient.id=${{ secrets.anypoint_client_id }} \
          -Dclient.secret=${{ secrets.anypoint_client_secret }} \
          -Denvironment=DEV \
          -Dtarget=${{ vars.target }} \
          -Drelease.channel=${{ vars.release_channel }} \
          -Dwire.logging.log.level=${{ vars.wire_logging_log_level }} \
          -Dreplicas=${{ vars.replicas }} \
          -Dvcores=${{ vars.vcores }}
